{
 "title": "Oracle",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(oracledb_cprobe_up,instance)"
    }
   },
   { "name": "interval", "query": "15s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_cprobe_up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$instance\", status=\"ACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "user commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "execute count / second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(oracledb_activity_execute_count{instance=\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "last scrape duration seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_cprobe_duration_seconds{instance=\"$instance\"}\t"
    }
   ]
  },
  {
   "title": "wait time concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "wait time commit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "wait time system io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "wait time user io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$instance\"}\t"
    }
   ]
  },
  {
   "title": "wait time application",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$instance\"}\t"
    }
   ]
  },
  {
   "title": "wait time network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$instance\"}\t"
    }
   ]
  }
 ]
}