{
 "title": "Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(blackbox_http_probe_result_code,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "blackbox_http_probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blackbox_http_probe_result_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "blackbox_http_probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blackbox_http_probe_response_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blackbox_http_cert_expire_timestamp{instance=~\"$target\"} - time()"
    }
   ]
  }
 ]
}